config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :address, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :image_url %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit "Update flat", class: "btn btn-primary" %>
      <% if @flat.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @flat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  <%= link_to "Cancel" , flats_path, class: "btn btn-danger mt-3" %>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1>All our flats</h1>
  <p>You searched for . We found <%= @flats.count %> flats out of our @flats.count on our website.</p>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="card m-3 shadow-sm mb-5 bg-white rounded" style="width: 21rem;">
      <img src= <%= flat.image_url %> class='card-img-top'>
      <div class="p-3">
        <h3><%= flat.name %></h3>
        <h6><%= flat.address %></h6>
        <div class="flex">
          <i class="fas fa-user-friends mx-2"></i>
          <%= flat.number_of_guests %>
          <i class="fas fa-euro-sign  mx-2"></i>
          <%= flat.price_per_night %>
        </div>
        <div class="flex px-3">
          <%= link_to "More info", flat_path(flat), class: "text-primary m-3" %>
          <%= link_to "Edit", edit_flat_path(flat), class: "text-warning m-3" %>
          <%= link_to "Remove", flat_path(flat), method: :delete, class: "text-danger m-3" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add new flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :image_url %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit "Add flat", class: "btn btn-primary" %>
      <% if @flat.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @flat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  <%= link_to "Cancel" , flats_path, class: "btn btn-danger mt-3" %>
</div>

app/views/flats/show.html.erb
<img src="https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200" class="" alt="Responsive image" width="100%" height=350px>
<div class="container mt-n5">
  <div class="row">
    <div class="col-8">
      <div class="card bg-white p-3">
        <h1><%= @flat.name %></h1>
        <h5><%= @flat.address %></h5>
        <br>
        <br>
        <h2>A bit more about this flat... </h2>
        <p><%= @flat.description  %></p>
      </div>
    </div>
    <div class="col-4">
      <div class="card bg-white px-1">
        <div class="bg-light p-3">
          <h2>Book this place</h2>
          <form action="#">
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">From:</span>
              <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
            </div>
            <div class="input-group mt-2">
              <span class="input-group-addon" id="basic-addon1">To:</span>
              <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
            </div>
            <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
          </form>
        </div>

        <div class="flex bg-light p-3">
          <h2>Details:</h2>
          <i class="fas fa-user-friends mx-2"></i>
          <%= @flat.number_of_guests %>
          <i class="fas fa-euro-sign  mx-2"></i>
          <%= @flat.price_per_night %>
        </div>
        <div class="flex-align">
          <h6>Share</h6>
          <div class="flex">
                      <i class="fab fa-facebook-square"></i>
            <i class="fab fa-twitter-square"></i>
            <i class="fab fa-pinterest-square"></i>
            <i class="fas fa-envelope-square"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <h3><%= link_to "Simple Airbnb", flats_path, class: "text-decoration-none text-reset"  %></h3>
      <%= link_to "Add flat", new_flat_path, class: 'btn btn-outline-primary' %>
    </div>
    <%= yield %>
  </body>
</html>